services:
  build:
    image: dohan4k/mkdocs-material:1.0
    build: 
      context: .
      dockerfile: Dockerfile

  mkdocs-material:
    depends_on:
      - build
    image: dohan4k/mkdocs-material:1.0
    container_name: mkdocs-dohan
    volumes:
      - .:/docs
    networks:
      - mkdocs-material-net
    ports:
      - 8080:8000
    restart: always

networks:
  mkdocs-material-net:
