# Project information
site_name: DevNotes by HAN
site_url: https://dohankwon.github.io

# Repository
repo_name: mkdocs
repo_url: https://github.com/dohankwon/mkdocs

edit_uri: edit/master/docs
docs_dir: "docs"
# site_dir: 'static'

# Theme
theme:
    name: material
    language: ko
    font:
        text: Roboto
        code: D2Coding
    # icon:
    #   logo: material/library
    features:
        - navigation.tabs
        - navigation.instant
        - navigation.expand
        - search.suggest
        - search.highlight
    palette:
        # Palette toggle for light mode
        - scheme: default
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
        # Palette toggle for dark mode
        - scheme: slate
          toggle:
              icon: material/weather-sunny
              name: Switch to light mode
    # palette:
    # scheme: default
    # primary: blue
    # accent: blue
    icon:
        repo: fontawesome/brands/github

# Plugins
plugins:
    - search
    - awesome-pages:
          filename: .pages
          # order: asc
          # order_by: title
          # sort_type: natural
          collapse_single_pages: true
          strict: true

extra_css:
    - css/custom.css

# Extensions
markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - meta
    - toc:
          permalink: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.snippets:
          check_paths: true
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.highlight:
          use_pygments: true
          pygments_lang_class: true
